version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./web:/var/www
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
  web:
    build: .
    environment:
      - "TZ=Asia/Tokyo"
    volumes:
      - ./web:/var/www
    ports:
      - 8081:8081
      - 3000:3000
  database:
    image: mysql:5.7.29
    environment:
      MYSQL_DATABASE: todoro
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      TZ: "Asiz/Tokyo"
    ports:
      - "3306:3306"
    volumes:
      - ./database:/var/lib/mysql
