version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@6.15.3

commands:
  assume_role:
    steps:
      - run:
          name: Assume Role
          command: |
            AWS_STS_CREDENTIALS="$(aws sts assume-role \
              --role-arn=${PROD_AWS_ASSUME_ROLE_ARN} \
              --role-session-name "CircleCI" \
              --external-id 00001 \
              --duration-seconds 1800 \
              --query "Credentials" \
              --output "json")"
            echo "export AWS_ACCESS_KEY_ID=$(echo ${AWS_STS_CREDENTIALS} | jq -r '.AccessKeyId')" >> ${BASH_ENV}
            echo "export AWS_SECRET_ACCESS_KEY=$(echo ${AWS_STS_CREDENTIALS} | jq -r '.SecretAccessKey')" >> ${BASH_ENV}
            echo "export AWS_SESSION_TOKEN=$(echo ${AWS_STS_CREDENTIALS} | jq -r '.SessionToken')"  >> ${BASH_ENV}

jobs:
  test:
    docker:
      - image: circleci/php:7.4.1-node-browsers
    working_directory: ~/todoro
    steps:
      - checkout
      - run:
          name: Update apt-get
          command: sudo apt-get update
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "~/todoro/web/composer.json" }}
            - v1-dependencies-
      - run:
          name: Install PHP libraries
          command: composer install -n --prefer-dist
          working_directory: ~/todoro/web
      - save_cache:
          paths:
            - ./vendor
          key: v1-dependencies-{{ checksum "~/todoro/web/composer.json" }}
      - run:
          name: Run PHPUnit
          command: vendor/bin/phpunit
          working_directory: ~/todoro/web

  build_and_push_image:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - assume_role
      - aws-ecr/build-and-push-image:
          account-url: AWS_ACCOUNT_URL
          aws-access-key-id: PROD_AWS_ACCESS_KEY_ID
          aws-secret-access-key: PROD_AWS_SECRET_ACCESS_KEY
          # repo: "${AWS_RESOURCE_NAME_PREFIX}-php"
          region: AWS_REGION
          tag: "${CIRCLE_SHA1}"
          # path:
          # dockerfile:

workflows:
  version: 2
  deploy:
    jobs:
      - test
      - build_and_push_image:
          requires:
            - test
          filters:
            branches:
              only:
                - master
                - feature/AssumeRoleAtCicleCI
