version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@6.15.3
jobs:
  test:
    docker:
      - image: circleci/php:7.4.1-node-browsers
    working_directory: ~/todoro
    steps:
      - checkout
      - run:
          name: Update apt-get
          command: sudo apt-get update
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "~/todoro/web/composer.json" }}
            - v1-dependencies-
      - run:
          name: Install PHP libraries
          command: composer install -n --prefer-dist
          working_directory: ~/todoro/web
      - save_cache:
          paths:
            - ./vendor
          key: v1-dependencies-{{ checksum "~/todoro/web/composer.json" }}
      - run:
          name: Run PHPUnit
          command: vendor/bin/phpunit
          working_directory: ~/todoro/web

  build_and_push_image:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - aws-ecr/build-and-push-image:
        account-url: "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}
          .amazonaws.com"
        repo: "${AWS_RESOURCE_NAME_PREFIX}-php"
        region: ${AWS_REGION}
        tag: "${CIRCLE_SHA1}"
        # path:
        # dockerfile:

workflows:
  version: 2
  deploy:
    jobs:
      - test
      - build_and_push_image:
        requires:
          - test
        filters:
          branches:
            only:
              - master
              - feature/pushForECRByCircleCI
